// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    feedback: { nodes: FeedbackTableRow[] };
  };

  type FeedbackTableRow = {
    id: string;
    title: string;
    description: string;
    vote: number;
    createdBy: CreatedByTableRow;
    slug: string;
    createdAt: Date;
    status: "ON PROGRESS" | "ICEBOX" | "DONE" | "TODO";
  };

  type AllFeedbackViewRow = {
    read: {
      id: string;
      title: string;
      description: string;
      vote: number;
      createdBy: CreatedByTableRow;
      slug: string;
      createdAt: Date;
      status: "ON PROGRESS" | "ICEBOX" | "DONE" | "TODO";
    };
    write: {
      title: string;
      description: string;
      vote: number;
      createdBy: string[];
      slug: string;
      createdAt: Date;
      status: "ON PROGRESS" | "ICEBOX" | "DONE" | "TODO";
    };
    params: {};
    actions: {};
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
    };
    write: {
      email: string;
    };
    params: {};
    actions: {};
  };

  type ProjectSchema = {
    allFeedback: AllFeedbackViewRow;
    allMember: AllMemberViewRow;
  };
}
